// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encoding.JobProto.proto

package encoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_Mobile PhoneType = 0
	PhoneType_host   PhoneType = 1
	PhoneType_worker PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "Mobile",
	1: "host",
	2: "worker",
}

var PhoneType_value = map[string]int32{
	"Mobile": 0,
	"host":   1,
	"worker": 2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60162a8250fe005b, []int{0}
}

type JobProto struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32       `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Emails               []string    `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Phones               []*PhoneNum `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JobProto) Reset()         { *m = JobProto{} }
func (m *JobProto) String() string { return proto.CompactTextString(m) }
func (*JobProto) ProtoMessage()    {}
func (*JobProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_60162a8250fe005b, []int{0}
}

func (m *JobProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobProto.Unmarshal(m, b)
}
func (m *JobProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobProto.Marshal(b, m, deterministic)
}
func (m *JobProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobProto.Merge(m, src)
}
func (m *JobProto) XXX_Size() int {
	return xxx_messageInfo_JobProto.Size(m)
}
func (m *JobProto) XXX_DiscardUnknown() {
	xxx_messageInfo_JobProto.DiscardUnknown(m)
}

var xxx_messageInfo_JobProto proto.InternalMessageInfo

func (m *JobProto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobProto) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *JobProto) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *JobProto) GetPhones() []*PhoneNum {
	if m != nil {
		return m.Phones
	}
	return nil
}

type PhoneNum struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=encoding.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNum) Reset()         { *m = PhoneNum{} }
func (m *PhoneNum) String() string { return proto.CompactTextString(m) }
func (*PhoneNum) ProtoMessage()    {}
func (*PhoneNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_60162a8250fe005b, []int{1}
}

func (m *PhoneNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNum.Unmarshal(m, b)
}
func (m *PhoneNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNum.Marshal(b, m, deterministic)
}
func (m *PhoneNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNum.Merge(m, src)
}
func (m *PhoneNum) XXX_Size() int {
	return xxx_messageInfo_PhoneNum.Size(m)
}
func (m *PhoneNum) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNum.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNum proto.InternalMessageInfo

func (m *PhoneNum) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNum) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_Mobile
}

func init() {
	proto.RegisterEnum("encoding.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*JobProto)(nil), "encoding.JobProto")
	proto.RegisterType((*PhoneNum)(nil), "encoding.PhoneNum")
}

func init() { proto.RegisterFile("encoding.JobProto.proto", fileDescriptor_60162a8250fe005b) }

var fileDescriptor_60162a8250fe005b = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x4d, 0xdb, 0x95, 0xf6, 0x0a, 0xa3, 0x5c, 0x41, 0xf3, 0x58, 0xf6, 0x62, 0x19, 0xd8,
	0x87, 0xf9, 0x2f, 0x14, 0x65, 0x04, 0xff, 0x40, 0x6b, 0x2f, 0x5b, 0x70, 0xc9, 0x0d, 0x69, 0x87,
	0xec, 0xdd, 0x1f, 0x2e, 0x89, 0xed, 0x7c, 0x09, 0xf7, 0x7c, 0xe7, 0x70, 0x38, 0x04, 0x1e, 0xc8,
	0x7e, 0xf2, 0xa0, 0xed, 0xa1, 0x7d, 0xe1, 0x7e, 0xef, 0x79, 0xe2, 0xd6, 0x85, 0x17, 0x8b, 0xc5,
	0xd8, 0xfc, 0x08, 0x28, 0x16, 0x13, 0xd7, 0x90, 0xe8, 0x41, 0x8a, 0x5a, 0x34, 0x2b, 0x95, 0xe8,
	0x01, 0x11, 0x32, 0xdb, 0x19, 0x92, 0x49, 0x2d, 0x9a, 0x52, 0xc5, 0x1b, 0x2b, 0x48, 0xbb, 0x03,
	0xc9, 0x34, 0x86, 0xc2, 0x89, 0xf7, 0x90, 0x93, 0xe9, 0xf4, 0x69, 0x94, 0x59, 0x9d, 0x36, 0xa5,
	0x9a, 0x15, 0x6e, 0x21, 0x77, 0x47, 0xb6, 0x34, 0xca, 0x55, 0x9d, 0x36, 0xb7, 0x3b, 0x6c, 0xaf,
	0x73, 0xf6, 0x81, 0xbf, 0x9f, 0x8d, 0x9a, 0x13, 0x9b, 0x57, 0x28, 0x16, 0x16, 0xfa, 0xec, 0xd9,
	0xf4, 0xe4, 0xe3, 0x92, 0x52, 0xcd, 0x0a, 0x1f, 0x21, 0x9b, 0x2e, 0xee, 0x6f, 0xcd, 0x7a, 0x77,
	0xf7, 0xdf, 0x16, 0x3b, 0x3e, 0x2e, 0x8e, 0x54, 0x0c, 0x6c, 0x9f, 0xa0, 0xbc, 0x22, 0x04, 0xc8,
	0xdf, 0xb8, 0xd7, 0x27, 0xaa, 0x6e, 0xb0, 0x80, 0xec, 0xc8, 0xe3, 0x54, 0x89, 0x40, 0xbf, 0xd9,
	0x7f, 0x91, 0xaf, 0x92, 0x3e, 0x8f, 0x7f, 0xf2, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x69, 0x36,
	0x99, 0x1e, 0x2e, 0x01, 0x00, 0x00,
}
